# Generated by Django 5.2.5 on 2025-09-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsControlClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('url_name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_name', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('view_class_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'fieldscontrol_class_info',
            },
        ),
        migrations.CreateModel(
            name='FieldsControlCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=70, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fieldscontrol_code',
            },
        ),
        migrations.CreateModel(
            name='FieldsControlErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('error_name', models.CharField(blank=True, max_length=100, null=True)),
                ('error_descriptions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fieldscontrol_errors',
            },
        ),
        migrations.CreateModel(
            name='FieldsControlFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fields_control', models.TextField(blank=True, null=True)),
                ('view_class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('class_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fieldscontrol.fieldscontrolclassinfo')),
            ],
            options={
                'db_table': 'fieldscontrol_fields',
            },
        ),
    ]
