# Generated by Django 5.2.5 on 2025-09-30 16:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_num', models.CharField(blank=True, max_length=25, null=True)),
                ('password', models.CharField(max_length=128)),
                ('sponsor_verified', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sponsors_photos/')),
            ],
            options={
                'db_table': 'verimed_sponsor_user',
            },
        ),
        migrations.CreateModel(
            name='VerimedDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_address', models.TextField(blank=True, null=True)),
                ('hospital_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dep_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dep_exprience', models.CharField(blank=True, max_length=100, null=True)),
                ('dep_logo', models.ImageField(blank=True, null=True, upload_to='department/')),
                ('dep_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'verimed_department',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('groups', models.ManyToManyField(blank=True, related_name='verimed_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='verimed_user_user_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'verimed_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SponsorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verimed_sponsorprofile',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
                ('sponsor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.sponsorprofile')),
            ],
            options={
                'db_table': 'verimed_patientprofile',
            },
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('password', models.CharField(max_length=128)),
                ('patient_verified', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients_photos/')),
                ('sponsor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.sponsoruser')),
            ],
            options={
                'db_table': 'verimed_patient_user',
            },
        ),
        migrations.CreateModel(
            name='VerimedDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('doc_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doc_address', models.TextField(blank=True, null=True)),
                ('doc_exprience', models.IntegerField(blank=True, null=True)),
                ('doc_photo', models.ImageField(blank=True, null=True, upload_to='doctor/')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.verimeddepartment')),
            ],
            options={
                'db_table': 'verimed_doctor',
            },
        ),
        migrations.CreateModel(
            name='VerimedBookAppoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('appoinment_date', models.DateField(blank=True, null=True)),
                ('appoinment_time', models.TimeField(blank=True, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('appoinment_reason', models.TextField(blank=True, null=True)),
                ('appoinment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='Pending', max_length=20, null=True)),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.verimeddepartment')),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.verimeddoctor')),
            ],
            options={
                'db_table': 'verimed_book_appoinment',
            },
        ),
    ]
