# Generated by Django 5.2.5 on 2025-10-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='patient_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='sponsor_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
