# Generated by Django 5.2.5 on 2025-10-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0003_patientprofile_patient_id_sponsorprofile_sponsor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'verimed_patientid',
            },
        ),
        migrations.CreateModel(
            name='SponsorID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sopnsor_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'verimed_sponsorid',
            },
        ),
    ]
