# Generated by Django 5.2.5 on 2025-10-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0004_patientid_sponsorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorid',
            old_name='sopnsor_id',
            new_name='sponsor_id',
        ),
    ]
