# Generated by Django 5.2.5 on 2025-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0005_rename_sopnsor_id_sponsorid_sponsor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('sponsor', 'Sponsor'), ('patient', 'Patient'), ('care_taker', 'Care Taker')], max_length=20, null=True),
        ),
    ]
