# Generated by Django 5.2.5 on 2025-10-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0008_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailverificationtoken',
            table='EmailVerificationToken',
        ),
    ]
