# Generated by Django 5.2.5 on 2025-10-02 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0009_alter_emailverificationtoken_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaretakerID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'verimed_caretakerid',
            },
        ),
        migrations.CreateModel(
            name='DoctorID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'verimed_doctorid',
            },
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='sponsor_user',
            new_name='sponsor',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='role',
            field=models.CharField(blank=True, choices=[('sponsor', 'Sponsor'), ('patient', 'Patient'), ('care_taker', 'Care Taker')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='emailverificationtoken',
            table='verimed_emailverificationtoken',
        ),
        migrations.CreateModel(
            name='CareTakerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker_verified', models.BooleanField(default=False)),
                ('caretaker_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verimed_caretakerprofile',
            },
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='caretaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.caretakerprofile'),
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_verified', models.BooleanField(default=False)),
                ('doctor_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verimed_doctorprofile',
            },
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.doctorprofile'),
        ),
    ]
