# Generated by Django 5.2.5 on 2025-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0010_caretakerid_doctorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='role',
            field=models.CharField(blank=True, choices=[('sponsor', 'Sponsor'), ('doctor', 'Doctor'), ('care_taker', 'Care Taker'), ('patient', 'Patient')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('sponsor', 'Sponsor'), ('doctor', 'Doctor'), ('care_taker', 'Care Taker'), ('patient', 'Patient')], max_length=20, null=True),
        ),
    ]
