# Generated by Django 5.2.5 on 2025-10-04 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0011_alter_emailverificationtoken_role_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.verimeddepartment'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doc_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doc_exprience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PatientUser',
        ),
        migrations.DeleteModel(
            name='SponsorUser',
        ),
    ]
