# Generated by Django 5.2.5 on 2025-10-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0012_doctorprofile_dep_doctorprofile_doc_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretakerprofile',
            name='care_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caretakerprofile',
            name='caretaker_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretakerprofile',
            name='caretaker_exprience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doc_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='sponsor_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='sponsor_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
