# Generated by Django 5.2.5 on 2025-10-04 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0013_caretakerprofile_care_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verimedbookappoinment',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.doctorprofile'),
        ),
    ]
