# Generated by Django 5.2.5 on 2025-10-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0014_alter_verimedbookappoinment_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='VerimedBookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('appointment_type', models.CharField(blank=True, max_length=150, null=True)),
                ('treatment_performed', models.CharField(blank=True, max_length=150, null=True)),
                ('lab_reports', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('care_taker_notes', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription_plan', models.CharField(blank=True, max_length=150, null=True)),
                ('height', models.CharField(blank=True, max_length=150, null=True)),
                ('weight', models.CharField(blank=True, max_length=150, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=150, null=True)),
                ('blood_sugar', models.CharField(blank=True, max_length=150, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('appointment_history', models.TextField(blank=True, null=True)),
                ('time_line', models.TextField(blank=True, null=True)),
                ('appointment_reason', models.TextField(blank=True, null=True)),
                ('appointment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='Pending', max_length=20, null=True)),
                ('caretaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.caretakerprofile')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.verimeddepartment')),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.doctorprofile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.patientprofile')),
            ],
            options={
                'db_table': 'verimed_book_appoinment',
            },
        ),
        migrations.DeleteModel(
            name='VerimedBookAppoinment',
        ),
    ]
