# Generated by Django 5.2.5 on 2025-10-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0015_patientprofile_blood_group_verimedbookappointment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verimedbookappointment',
            table='verimed_book_appoinments',
        ),
    ]
