# Generated by Django 5.2.5 on 2025-10-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0016_alter_verimedbookappointment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verimedbookappointment',
            name='lab_reports',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='VerimedBookAppointmentLabReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lab_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verimed_bookappointment_lab_reports_appointment', to='verimed.verimedbookappointment')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.patientprofile')),
            ],
            options={
                'db_table': 'verimed_book_appoinments_labreports',
            },
        ),
    ]
