# Generated by Django 5.2.5 on 2025-10-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0017_alter_verimedbookappointment_lab_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
