# Generated by Django 5.2.5 on 2025-10-05 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0018_alter_patientprofile_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verimedbookappointmentlabreports',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verimed_bookappointment_lab_reports_appointment', to='verimed.verimedbookappointment'),
        ),
    ]
