# Generated by Django 5.2.5 on 2025-10-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0019_alter_verimedbookappointmentlabreports_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='verimedbookappointmentlabreports',
            name='referid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
