# Generated by Django 5.2.5 on 2025-10-07 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0020_verimedbookappointmentlabreports_referid'),
    ]

    operations = [
        migrations.AddField(
            model_name='verimedbookappointment',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.sponsorprofile'),
        ),
    ]
