# Generated by Django 5.2.5 on 2025-10-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0021_verimedbookappointment_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='verimedCountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100, unique=True)),
                ('flag', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('dial_code', models.CharField(default='+000', max_length=10)),
            ],
            options={
                'db_table': 'verimed_countrycode',
            },
        ),
    ]
