# Generated by Django 5.2.5 on 2025-10-08 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0022_verimedcountrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.verimedcountrycode'),
        ),
    ]
