# Generated by Django 5.2.5 on 2025-10-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0023_user_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verimeddepartment',
            old_name='hospital_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='verimeddepartment',
            old_name='dep_category',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='verimeddepartment',
            old_name='dep_email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='verimeddepartment',
            old_name='dep_exprience',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='verimeddepartment',
            old_name='hospital_name',
            new_name='dep_ID',
        ),
        migrations.RemoveField(
            model_name='verimeddepartment',
            name='dep_logo',
        ),
        migrations.RemoveField(
            model_name='verimeddepartment',
            name='hospital_phone',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doc_country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.verimedcountrycode'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doc_licence_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doc_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='speciality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verimeddepartment',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='verimeddepartment',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.verimedcountrycode'),
        ),
        migrations.AddField(
            model_name='verimeddepartment',
            name='dep_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verimeddepartment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verimeddepartment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verimed.doctorprofile'),
        ),
        migrations.AddField(
            model_name='verimeddepartment',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verimeddepartment',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verimeddepartment',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='VerimedDoctor',
        ),
    ]
