# Generated by Django 5.2.5 on 2025-10-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0024_rename_hospital_address_verimeddepartment_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='city',
            new_name='doc_city',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='country',
            new_name='doc_country',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='pincode',
            new_name='doc_pincode',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='state',
            new_name='doc_state',
        ),
        migrations.RenameField(
            model_name='verimeddepartment',
            old_name='city',
            new_name='dep_city',
        ),
        migrations.RenameField(
            model_name='verimeddepartment',
            old_name='country',
            new_name='dep_country',
        ),
        migrations.RenameField(
            model_name='verimeddepartment',
            old_name='pincode',
            new_name='dep_pincode',
        ),
        migrations.RenameField(
            model_name='verimeddepartment',
            old_name='state',
            new_name='dep_state',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='address',
        ),
    ]
