# Generated by Django 5.2.5 on 2025-10-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0025_rename_city_doctorprofile_doc_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('sponsor', 'Sponsor'), ('doctor', 'Doctor'), ('care_taker', 'Care Taker'), ('patient', 'Patient')], max_length=20, null=True),
        ),
    ]
