# Generated by Django 5.2.5 on 2025-10-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0027_rename_patient_address_patientprofile_allergies_drug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientuploaddocuments',
            old_name='PatientProfile',
            new_name='patient_profile',
        ),
    ]
