# Generated by Django 5.2.5 on 2025-10-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0028_rename_patientprofile_patientuploaddocuments_patient_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientuploaddocuments',
            name='patient',
        ),
    ]
