# Generated by Django 5.2.5 on 2025-10-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0029_remove_patientuploaddocuments_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuploaddocuments',
            name='filename',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='patientuploaddocuments',
            table='patient_upload_documents',
        ),
    ]
