# Generated by Django 5.2.5 on 2025-10-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0030_patientuploaddocuments_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretakerprofile',
            name='credentials',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='caretakerprofile',
            name='skillset',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretakerprofile',
            name='yr_of_graduation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='how_found_us',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='work_employment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
