# Generated by Django 5.2.5 on 2025-10-17 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0032_doctorreports'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_verified', models.BooleanField(default=False)),
                ('admin_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('admin_address', models.TextField(blank=True, null=True)),
                ('admin_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verimed_adminprofile',
            },
        ),
    ]
