# Generated by Django 5.2.5 on 2025-10-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0033_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'verimed_adminid',
            },
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('sponsor', 'Sponsor'), ('doctor', 'Doctor'), ('care_taker', 'Care Taker'), ('patient', 'Patient')], max_length=20, null=True),
        ),
    ]
