# Generated by Django 5.2.5 on 2025-10-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0034_adminid_alter_emailverificationtoken_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminid',
            old_name='doctor_id',
            new_name='admin_id',
        ),
    ]
