# Generated by Django 5.2.5 on 2025-10-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0035_rename_doctor_id_adminid_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretakerprofile',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
