# Generated by Django 5.2.5 on 2025-10-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0036_caretakerprofile_title_patientprofile_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='verimedbookappointment',
            name='preferred_dates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='verimedbookappointment',
            name='preferred_times',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
