# Generated by Django 5.2.5 on 2025-10-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0037_verimedbookappointment_preferred_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorreports',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='doctorreports',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='doctorreports',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctorreports',
            name='country',
        ),
        migrations.RemoveField(
            model_name='doctorreports',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='doctorreports',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='doctorreports',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='doctorreports',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='doctorreports',
            name='state',
        ),
        migrations.RemoveField(
            model_name='doctorreports',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorreports',
            name='initial_visit',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='service_purchased',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='verimedbookappointment',
            name='service_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VerimedDoctorFileReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='doctorfilereports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('referid', models.CharField(blank=True, max_length=150, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verimed_doctor_file_reports', to='verimed.doctorreports')),
            ],
        ),
    ]
