# Generated by Django 5.2.5 on 2025-10-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0038_remove_doctorreports_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientprofile_countrycode', to='verimed.verimedcountrycode'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patientphotos/'),
        ),
    ]
