# Generated by Django 5.2.5 on 2025-10-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0039_patientprofile_country_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerimedDoctorFileReports',
            new_name='VerimedDoctorReportsFiles',
        ),
        migrations.RenameField(
            model_name='verimeddoctorreportsfiles',
            old_name='appointment',
            new_name='doc_report_files',
        ),
    ]
