# Generated by Django 5.2.5 on 2025-10-31 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0040_rename_verimeddoctorfilereports_verimeddoctorreportsfiles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='patient_id',
        ),
    ]
