# Generated by Django 5.2.5 on 2025-10-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0041_remove_patientprofile_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorprofile',
            name='service_purchased',
        ),
        migrations.AddField(
            model_name='user',
            name='service_purchased',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
