# Generated by Django 5.2.5 on 2025-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0044_patientprofile_age_patientprofile_blood_pressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='medication_dose',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medication_frequency',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medication_issues',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medication_issues_explain',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medication_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medication_reason',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medication',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
