# Generated by Django 5.2.5 on 2025-12-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0045_remove_patientprofile_medication_dose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField()),
                ('payment_intent', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
