# Generated by Django 5.2.5 on 2025-12-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verimed', '0046_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='verimed_contactus',
        ),
        migrations.AlterModelTable(
            name='order',
            table='verimed_order',
        ),
    ]
